### PR TITLE
Update branding.html.twig

### PR DESCRIPTION
**Pull request by PeopleInside**
Fix https://github.com/uvdesk/support-center-bundle/commit/79440b4048ea75b6d30441138192883fc6f64b13
Fix an error in the code.

### CODE REVIEW

**Comment by papnoisanjeev** [comment]
@PeopleInside 
Updated [here](https://github.com/uvdesk/support-center-bundle/commit/4bdf5d75f1b0614f91af6cc65094f4c5f1433000).

**Comment by PeopleInside** [comment]
Sorry, still have issue. 350 still give 500 error.
You should change to 340.

I'm testing, with 350 still give 500 error. Need reduce to 340 characters.

**Comment by papnoisanjeev** [comment]
@PeopleInside 
updated it to 300 character.
https://github.com/uvdesk/support-center-bundle/commit/d7d42b5b6429e2e49e3c1ecf52cb795a90f1ca35

**Comment by PeopleInside** [comment]
I don't know how many characters should be placed as max, IM testing if I get the exact number.

**Comment by papnoisanjeev** [comment]
@PeopleInside  
Check now it should work.

**Comment by PeopleInside** [comment]
Test done, with 300 still get 500 error. 

Tested and you need to set 200, 201 get 500 error.

200 max character.
You need also fix the world charectures that is wrong -> characters

**Comment by papnoisanjeev** [comment]
@PeopleInside 
> You need also fix the word charectures that is wrong -> characters
already fixed after last commit.
https://github.com/uvdesk/support-center-bundle/commit/76c7936764f8e38f78883ccb67506835f54b21b4

**Comment by PeopleInside** [comment]
@papnoisanjeev  just fix from 300 to 200 or still get 500 error.
I tested well this time and 201 characters will give 500 error

**Comment by papnoisanjeev** [comment]
@PeopleInside 
There is some other issue form your side change your environment and check what is the exact issue.
May be your database does not reflect with the changes we have done.

Just added approx. 290 characters and no error at all https://prnt.sc/123ecf9

**Comment by PeopleInside** [comment]
@papnoisanjeev I just update the php file and cleared cache. Need change something in the database?
i tested with 300 and still get 500 error so a fix should be not approx but should be precise.

What i just know with 200 I did not get 500 error I don't know what is the real max characters. I tried 300 ad still get 500 error.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Check your **uv_knowledgebase_website**  table  and it field type in your DB it should be longtext.
https://tinyurl.com/yzgs4kca

**Comment by PeopleInside** [comment]
I have varchar(255)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Yes it was the problem.

You don't need to change it from Database if you do https://github.com/uvdesk/community-skeleton/issues/393#issuecomment-826685359 the things we have suggested to you !!

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> Yes it was the problem.
> 
> You don't need to change it from Database if you do [uvdesk/community-skeleton#393 (comment)](https://github.com/uvdesk/community-skeleton/issues/393#issuecomment-826685359) the things we have suggested to you !!

I followed and the response by SSH was no database update necessary. I changed from phpmyadmin

**Pull request closed without merging**
