### PR TITLE
Update knowledgebase.css

### PR DESCRIPTION
**Pull request by PeopleInside**
Fix bad article visual where some text on the article have different dimension.
Text on articles should have the same dimension not some row more big and some row more smaller.

### CODE REVIEW

**Comment by papnoisanjeev** [comment]
@PeopleInside 
Thanks for your updates !!

Please share screenshot of before view and after view if you are making any change in CSS.

**Comment by PeopleInside** [comment]
As for your request the fix is for have all the article text of the same dimension.
You can see the following screen:

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Thanks for attachments, will soon merge the changes.
You can update other things as well for this if you found something else then finally we will merge in one shot.

**Comment by PeopleInside** [comment]
Sure, i made fix and test on my side.
If I found something wrong I still made fix also update my patch as well.

Thank you.

**Pull request merged**
